const { DataTypes } = require('sequelize');
const sequelize = require('./index');

const ImmigrationEvaluation = sequelize.define('ImmigrationEvaluation', {
  id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true },
  full_name: DataTypes.STRING,
  email: DataTypes.STRING,
  phone: DataTypes.STRING,
  date_of_birth: DataTypes.DATE,
  gender: DataTypes.STRING,
  country_of_birth: DataTypes.STRING,
  country_of_citizenship: DataTypes.STRING,
  country_of_residence: DataTypes.STRING,
  current_visa_status: DataTypes.STRING,
  highest_degree: DataTypes.STRING,
  major_field: DataTypes.STRING,
  university: DataTypes.STRING,
  graduation_year: DataTypes.STRING,
  occupation: DataTypes.STRING,
  employer: DataTypes.STRING,
  years_experience: DataTypes.STRING,
  job_duties: DataTypes.STRING,
  immigration_category: DataTypes.STRING,
  us_relatives: DataTypes.STRING,
  previous_visa_denials: DataTypes.STRING,
  additional_info: DataTypes.TEXT,
  created_at: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  title: DataTypes.STRING,
  title_other: DataTypes.STRING,
  visa_status_other: DataTypes.STRING,
  visa_expiration_date: DataTypes.STRING,
  field_esi: DataTypes.STRING,
  field_esi_other: DataTypes.STRING,
  degrees: DataTypes.JSON,
  degreesInProgress: DataTypes.JSON,
  employment_status: DataTypes.STRING,
  citation_profiles: DataTypes.STRING,
  citation_number: DataTypes.STRING,
  publication: DataTypes.STRING,
  published_year: DataTypes.STRING,
  no_publications: DataTypes.BOOLEAN,
  review_number: DataTypes.STRING,
  confirm_thank_you_email: DataTypes.BOOLEAN,
  owns_patents: DataTypes.STRING,
  patents: DataTypes.STRING,
  funding_received: DataTypes.STRING,
  fundingDetails: DataTypes.STRING,
  ongoing_project: DataTypes.STRING,
  ongoing_project_note: DataTypes.STRING,
  related_field_work: DataTypes.STRING,
  hears_form: DataTypes.JSON,
  read_notice: DataTypes.BOOLEAN,
  additional_comments: DataTypes.STRING,
}, {
  tableName: 'immigration_evaluations',
  timestamps: false,
});

module.exports = ImmigrationEvaluation;
